### ISSUE TITLE
For users (and editors) to find out more about relations how can the search be improved? 

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#206] opened 2019-01-30 13:18 UTC
![export-excel-scrnst](https://user-images.githubusercontent.com/25532142/51983786-e6114b00-2499-11e9-8f25-9343274b6bbc.png)

**Comment by Diederka** [comment] 2019-01-30 13:36
this question is similar to the question about the excel-export, which should also be used to edit via ruby-script. 
i know it's possible to query the relations via mysql. but normally users don't have access to mysql. 
so how can editors edit the data via script without knowing about the relations? 

For example, we have problems finding out which of our entities did not create relations in masseningest, and why. 
you can see this in the statistics, but we can't find out which entity "medium" e.g. has no connection to an entity "person". 
in a mysql-query excluding questions can be asked, but in the conedakor search this is not possible. 
therefore 2 questions: 
1) 
is it possible to get the relations by excel file? 
2) is it possible to establish a search function with boolean operators via browser? Then an exclusionary search could be made possible. Also an AND search or OR or NOT . This would be extremely helpful also for normal users.

**Comment by Diederka** [comment] 2019-02-03 09:42
Oh, I really didn't know, that there is no way, relations are exportable or editable. 
I know we can use the browser/ frontend for editing the data like properties and relations for that. But there is the aforementioned problem: to edit the errors in the data we have to have a better search function. otherwise we cant't find all flaws in relations or other errors... 
And the next question: if there is no export including relations possible. 
How can the full metadata be exported to be re-used?
I'm thinking about providing the data in different serializations (like RDF-XML). ...

**Comment by Diederka** [comment] 2019-02-03 09:47
> We are about to release v4.0, the code is already here on github (branch v4.0). This version exposes the full elasticsearch query syntax to the user, so searches like mona AND NOT lisa or "da vinci" -mona are possible.
THAT SOUNDS GREAT. 
I could use our given data for testing. 
I will take a look at that.

**Comment by moritzschepp** [comment] 2021-11-03 05:41
I close hoping that the issue is resolved by now, if not, please reopen.

**Closed by moritzschepp** 2021-11-03 05:41 UTC
Labels: question
