### ISSUE TITLE
error message: Could not find mini_portile2-2.3.0 in any of the sources Run `bundle install` to install missing gems.

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#176] opened 2018-06-07 16:29 UTC
after our host daasi reinstalled version 2.1.-pre 
i coulndt run the scripts any more. 
error ,message: 
```
Could not find mini_portile2-2.3.0 in any of the sources
Run `bundle install` to install missing gems.

```

**Comment by Diederka** [comment] 2018-06-08 10:43
First the problem was solved as I entered the command
RAILS_ENV=production bundle exec bin/kor import ../source_import.csv
for usind the import function of kor for our import scripts. 
But now the error message still comes back .
`Could not find mini_portile2-2.3.0 in any of the sources`
What shall I do?

**Comment by moritzschepp** [comment] 2018-06-10 01:56
Is this issue resolved? @drfbot, you wrote that things worked again after you installed the gem manually?

**Comment by Diederka** [comment] 2018-06-11 07:37
Unfortunately it worked only once. for running the first import_script. For the running second script the procedure was not reproducable.

**Comment by moritzschepp** [comment] 2018-06-15 00:38
As you can see in your `bundle install` output, the gem mini_portile2 was installed. How are you running your script exactly and what is your working directory while you are running it? Also, are you requiring other dependencies in the scripts than the kor environment?

**Comment by Diederka** [comment] 2018-06-15 08:09
Working directory is home/kor.  the scripts ar ein one folder, the csvs in another. 
I run them simply by calling for example `"ruby import_Artefacts+Relations.rb" `  
I don't recall other dependencies. 
Could it be a rights issue?

**Comment by Diederka** [comment] 2018-06-15 14:20
here a script example für artefact+relations (which is in home/kor/importfolder: 
`KOR_ROOT="/home/kor/kor/"
# import_Artefact+Relation.rb
# loading the rails environment

require "#{KOR_ROOT}/config/environment"
require 'json'

default = Collection.where(:name => 'Guest Collection').first
document = Kind.where(:name => 'Artefact').first

File.read("/home/kor/sourceFiles/source_import.csv").split("\n")[1..-1].each do |line|
  fields = line.split(";")

  jsonData = "{\"artefact_type\" : \"" + fields[16] + "\", \"artefact_type_in_twkm_database\" : \"" + fields[17] + "\", \"artefact_in_twkm_database\" : \"" + fields[18] + "\", \"catalogue_no\" : \"" + fields[19] + "\", \"publication\" : \"" + fields[20] + "\", \"zotero_publication_id\" : \"" + fields[21] + "\", \"inventory_no\" : \"" + fields[22] + "\", \"note\" : \"" + fields[23] + "\",
  \"artefact_is_depicted_by_medium\" : \"" + fields[1] + "\", \"artefact_was_located_in_place\" : \"" + fields[6] + "\", \"artefact_originates_from_archaeological_site\" : \"" + fields[12] + "\", \"artefact_was_documented_by_person\" : \"" + fields[24] + "\", \"artefact_was_held_by_collection\" : \"" + fields[8] + "\"}"

  jsonObj = JSON.parse(jsonData)
  #puts jsonData

  work = Entity.new(
    :kind => document,
    :collection => default,
    :name => fields[15],
    #:distinct_name => fields[16],
    :dataset => jsonObj
  )

  if work.valid?
    p work
    work.save
  else
    p work
    p work.errors.full_messages
  end
end
`

**Comment by Diederka** [comment] 2018-06-15 14:22
After installing budler it now says: 
`Could not find rake-12.3.1 in any of the sources`

**Comment by moritzschepp** [comment] 2018-06-16 01:56
I don't think permissions are the problem. The `bundle install` runs fine and installs the gems (somewhere) it just seems that the gems are not found when you run the script. Also, there is nothing else loaded in your script, just KOR (and json but that's part of the ruby stdlib, so no problem).

Can you run the following commands in sequence and post the output (just copy and paste the terminal window's contents after you ran the commands):

~~~ bash
rvm list
rbenv versions
ruby --version
gem list

cd /home/kor/kor
bundle install
# then run the script. If you need to run any commands before you can do that from here, make sure to include this in the pasted output.
~~~

**Comment by Diederka** [comment] 2018-06-17 18:02
`Output: commands made in in home/kor 


 [kor@classicmayan ~]$ ls
 cred.info                 importScripts_26.03.2018        make_kor_db_backup.sh
 IMAGES                    kor                             SCRIPTS
 IMAGESinJPG               kor_2017-11-09.tar.gz           sourceFiles
 importScripts_02.05.2018  kor.backup-2018-06              sqldump
 importScripts_07.06.2018  kor-postManipulation.sql        test
 importScripts_20.04.2018  kor-preManipulation2018-06.sql  uploadMedia.rb
 [kor@classicmayan ~]$ rvm list

 rvm rubies

 =* ruby-2.2.6 [ x86_64 ]
    ruby-2.4.1 [ x86_64 ]
    ruby-2.4.2 [ x86_64 ]

 # => - current
 # =* - current && default
 #  * - default

 [kor@classicmayan ~]$ 
 [kor@classicmayan ~]$ rbenv versions
 -bash: rbenv: Kommando nicht gefunden.
 [kor@classicmayan ~]$ 
 [kor@classicmayan ~]$ ruby --version
 ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-linux]
 [kor@classicmayan ~]$ 
 [kor@classicmayan ~]$ gem list

 *** LOCAL GEMS ***

 actionmailer (4.2.9)
 actionpack (4.2.9)
 actionview (4.2.9)
 activejob (4.2.9)
 activemodel (4.2.9)
 activerecord (4.2.9)
 activesupport (4.2.9)
 acts-as-taggable-on (3.5.0)
 addressable (2.5.1)
 angularjs-rails (1.5.6)
 arel (6.0.4)
 ast (2.2.0)
 awesome_nested_set (3.0.3)
 bigdecimal (default: 1.2.6)
 blankslate (3.1.3)
 brakeman (3.1.5)
 builder (3.2.3)
 bundler (1.16.2, 1.15.4)
 bundler-unload (1.0.2)
 capybara (2.15.1)
 childprocess (0.8.0, 0.7.1)
 climate_control (0.0.3)
 cliver (0.3.2)
 cocaine (0.5.8)
 coderay (1.1.0)
 coffee-rails (4.2.2)
 coffee-script (2.4.1)
 coffee-script-source (1.12.2)
 colorize (0.7.7)
 concurrent-ruby (1.0.5)
 crack (0.4.3)
 cucumber (2.4.0)
 cucumber-core (1.5.0)
 cucumber-rails (1.5.0)
 cucumber-wire (0.0.1)
 daemons (1.2.4)
 database_cleaner (1.5.3)
 debase-ruby_core_source (0.8.4)
 delayed_job (4.1.1)
 delayed_job_active_record (4.1.0)
 delayed_paperclip (2.9.1)
 diff-lcs (1.3)
 docile (1.1.5)
 erubis (2.7.0)
 eventmachine (1.2.5)
 execjs (2.7.0)
 executable-hooks (1.3.2)
 exifr (1.1.1)
 factory_girl (4.7.0)
 factory_girl_rails (4.7.0)
 fastercsv (1.5.5)
 ffi (1.9.18)
 gem-wrappers (1.2.7)
 gherkin (4.1.3)
 globalid (0.4.0)
 haml (4.0.7)
 hashdiff (0.3.4)
 highline (1.7.8)
 hirb (0.7.3)
 httpclient (2.7.1)
 i18n (0.8.4)
 image_magick (0.1.9)
 io-console (default: 0.4.3)
 jbuilder (2.4.1)
 jquery-rails (4.3.1)
 jquery-ui-rails (5.0.5)
 json (1.8.6, default: 1.8.1)
 libv8 (3.16.14.19 x86_64-linux)
 loofah (2.0.3)
 mail (2.6.6)
 method_profiler (2.0.1)
 method_source (0.8.2)
 mime-types (3.1)
 mime-types-data (3.2016.0521)
 mimemagic (0.3.0)
 mini_mime (0.1.4)
 mini_portile2 (2.2.0)
 minitest (5.10.2, 5.4.3)
 multi_json (1.12.1)
 multi_test (0.1.2)
 mysql2 (0.4.2)
 nokogiri (1.8.0)
 paperclip (4.3.6)
 paranoia (2.2.0)
 parser (2.3.0.7)
 parslet (1.7.1)
 passenger (5.1.8)
 plupload-rails (1.2.1)
 poltergeist (1.16.0)
 power_assert (0.2.7, 0.2.2)
 powerpack (0.1.1)
 pry (0.10.3)
 psych (default: 2.0.8)
 public_suffix (2.0.5)
 puma (3.9.1)
 quiet_assets (1.1.0)
 rack (1.6.8)
 rack-cors (0.4.0)
 rack-test (0.6.3)
 rails (4.2.9)
 rails-deprecated_sanitizer (1.0.3)
 rails-dom-testing (1.0.8)
 rails-html-sanitizer (1.0.3)
 railties (4.2.9)
 rainbow (2.1.0)
 rake (12.0.0, default: 10.4.2)
 rdoc (default: 4.2.0)
 RedCloth (4.3.2, 4.2.9)
 ref (2.0.0)
 responders (2.1.1)
 rspec-core (3.5.4)
 rspec-expectations (3.5.0)
 rspec-mocks (3.5.0)
 rspec-rails (3.5.2)
 rspec-support (3.5.0)
 rubocop (0.38.0)
 ruby-ole (1.2.12.1)
 ruby-progressbar (1.7.5)
 ruby2ruby (2.2.0)
 ruby_parser (3.7.3)
 rubygems-bundler (1.4.4)
 rubygems-update (2.7.7)
 rubyzip (1.2.1)
 rvm (1.11.3.9)
 safe_yaml (1.0.4)
 sass (3.4.24)
 sass-rails (5.0.6)
 selenium-webdriver (3.5.2, 3.5.0)
 sexp_processor (4.7.0)
 simplecov (0.11.2)
 simplecov-html (0.10.0)
 slim (3.0.6)
 slop (3.6.0)
 spreadsheet (1.1.4)
 sprockets (3.7.1)
 sprockets-rails (3.2.0)
 temple (0.7.6)
 terminal-table (1.5.2)
 test-unit (3.1.7, 3.0.8)
 test_after_commit (1.1.0)
 therubyracer (0.12.3)
 thin (1.7.2)
 thor (0.19.4)
 thread_safe (0.3.6)
 tilt (2.0.7)
 tzinfo (1.2.3)
 uglifier (2.7.2)
 unicode-display_width (1.0.2)
 vcr (3.0.3)
 webmock (3.0.1)
 websocket-driver (0.6.5)
 websocket-extensions (0.1.2)
 will_paginate (3.0.7)
 xpath (2.1.0)
 [kor@classicmayan ~]$ 
 [kor@classicmayan ~]$ cd /home/kor/kor
 [kor@classicmayan kor]$ 
 [kor@classicmayan kor]$ pwd
 /home/kor/kor
 [kor@classicmayan kor]$ bundle install
 Using rake 12.3.1
 Using RedCloth 4.3.2
 Using concurrent-ruby 1.0.5
 Using i18n 0.9.5
 Using minitest 5.11.3
 Using thread_safe 0.3.6
 Using tzinfo 1.2.5
 Using activesupport 4.2.10
 Using builder 3.2.3
 Using erubis 2.7.0
 Using mini_portile2 2.3.0
 Using nokogiri 1.8.2
 Using rails-deprecated_sanitizer 1.0.3
 Using rails-dom-testing 1.0.9
 Using crass 1.0.4
 Using loofah 2.2.2
 Using rails-html-sanitizer 1.0.4
 Using actionview 4.2.10
 Using rack 1.6.10
 Using rack-test 0.6.3
 Using actionpack 4.2.10
 Using globalid 0.4.1
 Using activejob 4.2.10
 Using mini_mime 1.0.0
 Using mail 2.7.0
 Using actionmailer 4.2.10
 Using activemodel 4.2.10
 Using arel 6.0.4
 Using activerecord 4.2.10
 Using acts-as-taggable-on 3.5.0
 Using public_suffix 3.0.2
 Using addressable 2.5.2
 Using angularjs-rails 1.5.8
 Using ast 2.4.0
 Using awesome_nested_set 3.0.3
 Using backports 3.11.3
 Using brakeman 4.3.1
 Using bundler 1.16.2
 Using xpath 3.1.0
 Using capybara 3.2.1
 Using ffi 1.9.25
 Using childprocess 0.9.0
 Using climate_control 0.2.0
 Using coderay 1.1.2
 Using coffee-script-source 1.12.2
 Using execjs 2.7.0
 Using coffee-script 2.4.1
 Using thor 0.20.0
 Using railties 4.2.10
 Using coffee-rails 4.2.2
 Using colorize 0.8.1
 Using safe_yaml 1.0.4
 Using crack 0.4.3
 Using cucumber-tag_expressions 1.1.1
 Using gherkin 5.1.0
 Using cucumber-core 3.1.0
 Using cucumber-expressions 6.0.0
 Using cucumber-wire 0.0.1
 Using diff-lcs 1.3
 Using multi_json 1.13.1
 Using multi_test 0.1.2
 Using cucumber 3.1.1
 Using mime-types-data 3.2016.0521
 Using mime-types 3.1
 Using cucumber-rails 1.6.0
 Using daemons 1.2.6
 Using database_cleaner 1.7.0
 Using debase-ruby_core_source 0.10.3
 Using delayed_job 4.1.5
 Using delayed_job_active_record 4.1.3
 Using mimemagic 0.3.2
 Using terrapin 0.6.0
 Using paperclip 6.0.0
 Using delayed_paperclip 3.0.1
 Using docile 1.3.1
 Using eventmachine 1.2.7
 Using exifr 1.1.1
 Using factory_girl 4.9.0
 Using factory_girl_rails 4.9.0
 Using temple 0.8.0
 Using tilt 2.0.8
 Using haml 5.0.4
 Using hashdiff 0.3.7
 Using hirb 0.7.3
 Using httpclient 2.8.3
 Using jaro_winkler 1.5.1
 Using jbuilder 2.7.0
 Using jquery-rails 4.3.3
 Using jquery-ui-rails 6.0.1
 Using json 2.1.0
 Using kor_index 0.0.1 from source at `plugins/kor_index`
 Using libv8 3.16.14.19 (x86_64-linux)
 Using method_profiler 2.0.1
 Using method_source 0.9.0
 Using mysql2 0.4.10
 Using parallel 1.12.1
 Using paranoia 2.4.1
 Using parser 2.5.1.0
 Using parslet 1.8.2
 Using sprockets 3.7.1
 Using sprockets-rails 3.2.1
 Using rails 4.2.10
 Using plupload-rails 1.2.1
 Using power_assert 1.1.2
 Using powerpack 0.1.2
 Using pry 0.11.3
 Using puma 3.11.4
 Using quiet_assets 1.1.0
 Using rack-cors 1.0.2
 Using rainbow 3.0.0
 Using rb-fsevent 0.10.3
 Using rb-inotify 0.9.10
 Using ref 2.0.0
 Using responders 2.4.0
 Using rspec-support 3.5.0
 Using rspec-core 3.5.4
 Using rspec-expectations 3.5.0
 Using rspec-mocks 3.5.0
 Using rspec-rails 3.5.2
 Using ruby-progressbar 1.9.0
 Using unicode-display_width 1.4.0
 Using rubocop 0.57.2
 Using ruby-ole 1.2.12.1
 Using rubyzip 1.2.1
 Using sass-listen 4.0.0
 Using sass 3.5.6
 Using sass-rails 5.0.7
 Using selenium-webdriver 3.12.0
 Using simplecov-html 0.10.2
 Using simplecov 0.16.1
 Using spreadsheet 1.1.7
 Using test-unit 3.2.8
 Using test_after_commit 1.1.0
 Using therubyracer 0.12.3
 Using thin 1.7.2
 Using uglifier 4.1.11
 Using vcr 4.0.0
 Using webmock 3.4.2
 Using will_paginate 3.0.12
 Bundle complete! 53 Gemfile dependencies, 139 gems now installed.
 Use `bundle info [gemname]` to see where a bundled gem is installed.
 [kor@classicmayan kor]$ cd ..
 [kor@classicmayan ~]$ ls
 cred.info                 importScripts_26.03.2018        make_kor_db_backup.sh
 IMAGES                    kor                             SCRIPTS
 IMAGESinJPG               kor_2017-11-09.tar.gz           sourceFiles
 importScripts_02.05.2018  kor.backup-2018-06              sqldump
 importScripts_07.06.2018  kor-postManipulation.sql        test
 importScripts_20.04.2018  kor-preManipulation2018-06.sql  uploadMedia.rb
 [kor@classicmayan ~]$ cd importScripts_07.06.2018
 [kor@classicmayan importScripts_07.06.2018]$ ruby import_Place+Relation.rb 
 Could not find rake-12.3.1 in any of the sources
 Run `bundle install` to install missing gems.`

**Comment by moritzschepp** [comment] 2018-06-18 00:48
Thanks, that should give us some idea of what's going on:

It seems the bundle is installed elsewhere than the system's location for gems: `bundle install` says "Using rake 12.3.1" while `gem list` lists "rake (12.0.0, default: 10.4.2)". "Using ..." means the gem is already installed so bundler didn't have to install it. Probably the bundle had previously been installed to a specific path with something like `bundle install --path /some/path`. This creates a file ".bundle/config" which stores /some/path for further runs of `bundle install`. You can check if this file is there with `cat /home/kor/kor/.bundle/config`.

If the above is really the problem then I see two ways to get your scripts running again:

Either make sure to always use this .bundle/config. That involves calling all scripts from /home/kor/kor, e.g.:

    cd /home/kor/kor
    ruby ../importScripts_07.06.2018/import_Place+Relation.rb

... or remove the .bundle/config and use the system's (in your case rvm's gem install directory), so:

    cd /home/kor/kor
    rm .bundle/config
    bundle install
    # the above is only necessary once, from then on, you should be able
    # to call the script from everywhere, so for example, as you did before:
    cd ..
    cd importScripts_07.06.2018
    ruby import_Place+Relation.rb

The second solution requires that you have write permission to the system's gem install directory. Contact your admin if you get errors like "permission denied".

Does this help?

**Comment by Diederka** [comment] 2018-06-18 06:17
Hmmm, I checked with `cat /home/kor/kor/.bundle/config`
but it found nothing. 
`[kor@classicmayan kor]$ cat /home/kor/kor/.bundle/config
cat: /home/kor/kor/.bundle/config: Datei oder Verzeichnis nicht gefunden`

**Comment by moritzschepp** [comment] 2018-06-19 03:05
Bizarre .. is there `/home/kor/importScripts_07.06.2018/Gemfile` or `/home/kor/importScripts_07.06.2018/.bundle/config`? Does calling the script from within the KOR directory work?

**Comment by Diederka** [comment] 2018-06-19 06:10
I only see in home/kor: 
`[kor@classicmayan ~]$ ls -l
insgesamt 9434592
-rw-r--r--  1 root root         24 23. Mär 10:44 cred.info
drwxrwxr-x  2 kor  kor       57344  5. Jun 12:10 IMAGES
drwxrwxr-x  2 kor  kor     1011712  5. Jun 12:21 IMAGESinJPG
drwxrwxr-x  2 kor  kor        4096  2. Mai 16:20 importScripts_02.05.2018
drwxr-xr-x  2 kor  kor        4096  8. Jun 12:12 importScripts_07.06.2018
drwxrwxr-x  2 kor  kor        4096 28. Apr 10:40 importScripts_20.04.2018
drwxrwxr-x  3 kor  kor        4096 25. Apr 14:53 importScripts_26.03.2018
drwxr-xr-x 22 kor  kor        4096 12. Jun 11:26 kor
-rw-r--r--  1 root root 9657335225  9. Nov 2017  kor_2017-11-09.tar.gz
drwxr-xr-x  3 root root       4096  7. Jun 16:36 kor.backup-2018-06
-rw-r--r--  1 root root     821884 12. Jun 09:52 kor-postManipulation.sql
-rw-r--r--  1 root root    1730525  7. Jun 16:23 kor-preManipulation2018-06.sql
-rwxr-xr--  1 root root        643  7. Sep 2017  make_kor_db_backup.sh
drwxrwxr-x  5 kor  kor        4096 30. Jan 11:24 SCRIPTS
drwxrwxr-x  2 kor  kor        4096  5. Jun 20:04 sourceFiles
drwxr-xr-x  2 root root       4096 19. Jun 03:03 sqldump
drwxrwxr-x  2 kor  kor        4096  7. Jun 19:55 test
-rw-rw-r--  1 kor  kor         973 28. Mai 13:37 uploadMedia.rb`
and in the script folder: 
`[kor@classicmayan ~]$ ls -l importScripts_07.06.2018/
insgesamt 76
-rw-r--r-- 1 kor kor  855 24. Mai 14:27 artefact_originates_from_archaeological_site.rb
-rw-r--r-- 1 kor kor  724 24. Mai 14:28 artefact_was_documented_by_person.rb
-rw-r--r-- 1 kor kor  766  6. Jun 20:31 artefact_was_held_by_collection.rb
-rw-r--r-- 1 kor kor  728  6. Jun 20:14 artefact_was_located_in_place.rb
-rw-r--r-- 1 kor kor  737  6. Jun 20:26 collection_was_held_by_holder.rb
-rw-r--r-- 1 kor kor 1401  6. Jun 20:33 import_Artefact+Relation.rb
-rw-r--r-- 1 kor kor  955  8. Jun 11:39 import_Collection+Relation.rb
-rw-r--r-- 1 kor kor  860  6. Jun 20:25 import_Holder+Relation.rb
-rw-r--r-- 1 kor kor 1361  8. Jun 11:46 import_Medium+Relation.rb
-rw-r--r-- 1 kor kor  890  6. Jun 20:37 import_Person+Relation.rb
-rw-rw-r-- 1 kor kor 1043  8. Jun 11:44 import_Place+Relation.rb
-rw-r--r-- 1 kor kor  916 24. Mai 15:07 import_Site+Relation.rb
-rw-r--r-- 1 kor kor  682 24. Mai 15:12 medium_depicts_artefact.rb
-rw-r--r-- 1 kor kor  683  8. Jun 12:12 medium_was_created_at_place.rb
-rw-r--r-- 1 kor kor  690 24. Mai 15:15 medium_was_created_by_person.rb
-rw-r--r-- 1 kor kor  738  8. Jun 12:12 medium_was_created_from_collection.rb
-rw-r--r-- 1 kor kor  678  8. Jun 12:12 place_located_collection.rb
-rw-r--r-- 1 kor kor  669  6. Jun 20:16 place_located_holder.rb
-rw-r--r-- 1 kor kor  679 24. Mai 15:17 place_was_visited_by_person.rb`

**Comment by MaximilianBrodhun** [comment] 2018-06-19 08:12
Hello Moritz,

I come into the discussion to coordinate the stuff better.

A first thing in generell, when I do "bundle update" everything works fine. But I need to have to be member in the sudo group and that was just for a short term granted. Of course I can get it once again.

The Gemfile ist located is in /home/kor/kor/Gemfile and looks like this:


`source 'https://rubygems.org'

gem 'rails', '~> 4.2.6'
gem 'responders', '~> 2.0'

gem 'delayed_paperclip'
gem 'paperclip'
gem 'terrapin'
gem 'daemons'
gem 'mysql2', '~> 0.4.4'
gem 'RedCloth'
gem 'will_paginate', '~> 3.0.3'
gem 'parslet'
gem 'exifr', '1.1.1'
gem 'haml'
gem 'sass'
gem 'httpclient'
gem 'acts-as-taggable-on', '~> 3.5'
gem 'hirb'

gem 'sprockets-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'angularjs-rails', '~> 1.5.2'
gem 'plupload-rails'
gem 'coffee-rails'
gem 'sass-rails'

gem 'jbuilder'
gem 'test-unit'
gem 'ruby-progressbar'
gem 'colorize'
gem 'rack-cors', :require => 'rack/cors'

if !ENV['RAILS_GROUPS'] || !ENV['RAILS_GROUPS'].match(/assets/)
  # TODO: all of these load activerecord on asset precompiliation so we load
  # (and configure) it in app/controllers/application_controller.rb
  gem "paranoia", "~> 2.2"
  gem 'delayed_job_active_record'
  gem 'awesome_nested_set', '~> 3.0.0'
  gem 'factory_girl_rails'
end

gem 'kor_index', path: './plugins/kor_index'

group :test do
  gem 'cucumber-rails', require: false
  gem 'selenium-webdriver'
  gem 'rspec-rails', '~> 3.5.2'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'vcr'
  gem 'webmock'
  gem 'simplecov', require: false
  gem 'test_after_commit'
end

group :development do
  gem 'method_profiler'
  gem 'debase-ruby_core_source'
  # gem 'perftools.rb'
  gem 'rubocop', require: false
  gem 'brakeman', require: false
end

group :test, :development do
  gem 'thin'
  gem 'quiet_assets'
  gem 'pry'
end

group :production do
  gem 'puma'
end

group :production, :test do
  gem 'therubyracer'
  gem 'uglifier'
end

group :import_export do
  gem 'spreadsheet'
end
`

I changed the line  gem 'mysql2', '~> 0.4.4' because with a newer version it didn't work.

**Comment by moritzschepp** [comment] 2018-06-19 09:31
Hi Max :)

Its certainly not right that you would have to make modifications to the Gemfile at all. If I understand correctly, you are on CentOS 7. I just set one up and installed some basic packages and then the gems install fine and KOR runs without problems. Please have a look at the setup script at https://github.com/coneda/kor/blob/master/deploy/vagrant.centos.sh, its very short. Can your clarify what didn't work with the original Gemfile and Gemfile.lock?

`bundle update` updates ALL gems in Gemfile.lock to the latest possible versions according to Gemfile. This is certainly not what you want to run. If you need to install gems while not having the required permissions, you may install the "bundle" into a specific directory. For example, you can do this:

    bundle install --path /path/to/some/dir --without development test

`--without development test` limits the installed gems to those required in production, leaving out testing libraries and development dependencies. However, this bundle can only be used if you are in that directory when running scripts.

**Comment by MaximilianBrodhun** [comment] 2018-07-17 11:54
Hi Moritz,

sorry for the late reply. But the problem is still the same.
I install the gems into the path "/home/kor/gemtest", copy the ruby import script into "/home/kor/gemtest", but the error message is still the same:

```
Could not find rake-12.3.1 in any of the sources
Run `bundle install` to install missing gems.
```

bundle install of course not possible without the Gemfile.

**Comment by moritzschepp** [comment] 2021-11-03 05:30
I close hoping that the issue is resolved by now, if not, please reopen.

**Closed by moritzschepp** 2021-11-03 05:30 UTC
Labels: question
