### ISSUE TITLE
How to address entities via url?

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#243] opened 2019-04-27 21:16 UTC
I have another question about mapping the data for using/displaying them in the DDB: 
In LIDO, the DDB expects a link to the digital record (here: an entity) "/lido:lidoWrap/lido:lido/lido:administrativeMetadata/lido:recordWrap/lido:recordInfoSet/lido:recordInfoLink".  
and a link to the digital representation (here: digitized photography as medium) in "/lido:lidoWrap/lido:lido/lido:administrativeMetadata/lido:resourceWrap/lido:resourceSet/lido:resourceRepresentation/lido:linkResource". 
This means it must be possible to link the images as well as links to the other entities online like Place, Artefact, Collection etc..
Via the OAI interface the media are adressable. 
-> `<kor:image-path` `style="original">
https://classicmayan.kor.de.dariah.eu/media/download/original/1318`
But via OAI only the identifier of other entitities can be found (e.g. the id="61ef9529-d8bd-4f5d-bdb5-88ac2ee89210" for the place Acaneh) but how can I enter the direct link to this entity as value in LIDO under "lido:recordInfoLink"? 
So where do I get the direct links to other entities?

**Comment by moritzschepp** [comment] 2019-04-30 21:39
Hmm, I don't know really, I have too little experience with LIDO. @wuebbena can you help?

**Comment by Diederka** [comment] 2019-05-01 08:24
The LIDO record has to look like so: 
``` xml
<lido:recordWrap>
     <lido:recordInfoSet>
          <lido:recordInfoLink lido:formatResource="text/html">http://xxx is a URL resolvable from UUID??? </lido:recordInfoLink>
     </lido:recordInfoSet>
</lido:recordWrap>
```

**Comment by Diederka** [comment] 2019-05-01 16:25
My wrongly posted question in issue 244 belonged in this thread: 
I wrote
> Or do I misunderstand something? is there a way to automatically build a link via the ID (the UUID in the masterdata) to the respective entity?
> Or are these informations in the harvested data?
> As yo mentioned in #239, there is a way to harvest all data (which I haven't used yet).

**Comment by moritzschepp** [comment] 2019-05-01 16:40
So for example, the entity 314661 at KHI Frankfurt has several urls:

* https://kor.uni-frankfurt.de/blaze#/entities/314661 (for the browser, by internal id)
* https://kor.uni-frankfurt.de/blaze#/entities/1c0128ac-28f0-4e3d-b6c7-44110ed47465 (for the browser, by uuid)
* https://kor.uni-frankfurt.de/entities/314661.json (json format, by internal id)
* https://kor.uni-frankfurt.de/entities/1c0128ac-28f0-4e3d-b6c7-44110ed47465.json (json format, by uuid)
* https://kor.uni-frankfurt.de/api/oai-pmh/entities.xml?verb=GetRecord&identifier=1c0128ac-28f0-4e3d-b6c7-44110ed47465&metadataPrefix=kor (oai pmh, by uuid)

Is that what you need?

**Comment by Diederka** [comment] 2019-05-01 17:10
Yes, that's what I searched for. 
I recently learned to get records via OAI, (your last example,  but I did only find the kor:id there, but no genuine link to the entity in the database. 
Well maybe I think wrong here and the harvesting organisation doesn't need the link to the entity in the database (and the media) but I understood that they need them. 
But if they really needed the URL, now I see your several examples and as I understand, there is a way to construct the URL with the help of the given OAI data. If it were necessary: When the DDB harvests our data via OAI they only have to construct the URL out of the IDs (which are UUIDs) using a fix prefix? 
For example the OAI data gives us the ID in the header or in the metadata  e.g. 
`<kor:id>c0912b1b-35a0-40f6-80c4-b0fde8dd24f1</kor:id>`
and they construct the prefix: 
 `https://classicmayan.kor.de.dariah.eu/blaze#/entities/` 
and put the kor:id behind?

**Comment by moritzschepp** [comment] 2019-05-01 17:37
The browser urls will change, for example in v4, the `/blaze` prefix is gone. The oai-pmh urls also change (no `/api` prefix). If you want something stable that doesn't change over time, you could also use https://classicmayan.kor.de.dariah.eu/resolve/uuid/c0912b1b-35a0-40f6-80c4-b0fde8dd24f1 which redirects to the browser url.

**Comment by moritzschepp** [comment] 2019-05-01 17:38
Any such change would happen in a major release, e.g. from v3 to v4 but not from v4 to v4.1.

**Comment by Diederka** [comment] 2019-05-01 17:39
oh good! I will askt the team from the DDB if this is good. 
And what about the links to images?

**Comment by moritzschepp** [comment] 2019-05-01 17:45
The urls from https://classicmayan.kor.de.dariah.eu/api/oai-pmh/entities.xml?verb=GetRecord&identifier=c71777d0-bf00-45c5-b024-2ad0e795ba8e&metadataPrefix=kor don't work?

**Comment by Diederka** [comment] 2019-05-01 17:51
yes they work, and I get to the medium entity. but maybe I also misunderstand something here. But in the oai data there are several links to the orignal medium, the thumbnail etc. 
but these are download links like e.g. this one: 
`<kor:image-path style="original">
https://classicmayan.kor.de.dariah.eu/media/download/original/6249
</kor:image-path>`
So they demand the URL to the link for LIDO,  and my question, is this okay for the DDB to get the download link? or do they need a "normal" link?

**Comment by moritzschepp** [comment] 2019-05-01 17:58
I don't know what the DDB needs or what LIDO requires, but perhaps @wuebbena knows.

If you are worried to hand over access to your original files, you can control access to those (independently) via the collection editor.

**Comment by Diederka** [comment] 2019-05-01 18:02
Oh no, I want the DDB to use the links to provide a link to the original (they write: Objekt beim Datengeber anzeigen"). 
See: 
[https://www.deutsche-digitale-bibliothek.de/item/OIRPABME6BNEYXYBOVJOBID7AFUZXQ5G?isThumbnailFiltered=true&query=&rows=20&offset=0&viewType=list&sort=random_1483817117836682989&firstHit=POEXF4CE4HFWV72KQRH5NVD2NRY7HVML&lastHit=lasthit&hitNumber=6](url)

**Comment by moritzschepp** [comment] 2021-11-03 05:41
I close hoping that the issue is resolved by now, if not, please reopen.

**Closed by moritzschepp** 2021-11-03 05:41 UTC
Labels: question
