### ISSUE TITLE
is it possible to attach metadata to a  medium at download automatically

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#159] opened 2018-03-16 12:33 UTC
We have two questions: 
1) if someone downloads a picture from our db, we want to have the rights be downloaded with it. 
so our first question ist: 
can we write the terms of use into the metadata? for now, only the UUID of a picture is given there. 
2) can we make the metadata be attached automatically to the picture at download? so that the user always downloads two files, the data and the metadata. 
And another question: 
If it is not possible, can we let the rights be written into the exif files? 

For our scenario the example would be: 
Image with filename KHM1234.tiff is downloaded. 
Ithe metadata we want to be written the Infos like so: 
"KHM1234.tiff, CC by 4.0  Karl Herbert Mayer, provided by Project Textdatabase and dictionary of Classic Mayan,  Bonn (2018)"

Another question: 
If an automatically writable metadata is possible. 
Could we fill the fields for "medium.title" (KHM1234.tiff) and "person.name" (Karl Herbert Mayer) into the otherwise static text dynamically?

**Comment by moritzschepp** [comment] 2018-03-17 07:29
1. The metadata download should include the names of primary and secondary entities together with the medium's uuid. That is the data also shown under "new entries".
2. Media downloads always deliver the medium file directly and metadata downloads always yield a text file. If users download media via zip download (e.g. by downloading a group), the (above) metadata is included within the zip file.
3. Only the medium uuid and the names of primary and secondary entities are included within the metadata.

If you require more customized metadata, I recommend placing specially generated text files into the application's document root directory. The webserver can then be configured to serve those files instead of the default metadata. So, for example, at `/12345/metadata`.

**Comment by moritzschepp** [comment] 2021-11-03 05:38
I close hoping that the issue is resolved by now, if not, please reopen.

**Closed by moritzschepp** 2021-11-03 05:38 UTC
Labels: question
