### ISSUE TITLE
why can't the link resolver mechanism in conedakor map urls that contain a dot? 

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#232] opened 2019-04-02 13:28 UTC
why can't the link resolver mechanism in conedakor map urls that contain a dot? 
Normally it is like this with us: The field "image_number" is the identifier and therefore a URI can be resolved by generator from the value in it. 
These URIs can serve as permalinks to the images (at least to their entities).
See picture with the number "KHM_1976_F10_R06_25" ->
https://classicmayan.kor.de.dariah.eu/resolve/image_no/KHM_1976_F10_R06_25
 
Now we have a problem with the transfer of external pictures into our archive ... 
Here there is e.g. the following external source: 
"https://d1lfxha3ugu3d4.cloudfront.net/images/opencollection/objects/size4/2002.33a-b_view1_bw.jpg"
We have now described the artefact and all related media in our database. 
But with media like this there is a problem: 
https://classicmayan.kor.de.dariah.eu/blaze#/entities/17624
The image number is entered in the field "image_number". 
"Image Number: BMN_2002.33a-b_view1_bw" 
However, unfortunately it contains a dot, and thus also in the generated in the URL, and this poses a problem for the mapping of the link in cor. It can not be shown.  
Is this changeable in the cor-code, or may no dot (and other certain characters) enter into this field?

**Comment by moritzschepp** [comment] 2019-04-07 19:09
I understand: https://classicmayan.kor.de.dariah.eu/resolve/image_no/BMN_2002.33a-b_view1_bw should resolve to https://classicmayan.kor.de.dariah.eu/blaze#/entities/17624 but renders an error instead.

This is a bug. I'll fix it shortly. I think this is happening because the rails framework interprets everything after the dot as a format (e.g json, html, xml etc) and therefore excludes the dot from id parameter fragments.

**Comment by moritzschepp** [comment] 2019-04-07 19:25
I've just looked into this and I couldn't reproduce the problem in a test environment. The dot seems to pose no problem. Can you get the relevant part from production.log from when the error is shown?

**Comment by Diederka** [comment] 2019-04-08 20:20
that is strange. this resolver doesnt't work in my browser. https://d1lfxha3ugu3d4.cloudfront.net/images/opencollection/objects/size4/2002.33a-b_view1_bw.jpg
There is no error log. I only use the frontend , I use the browser.

**Comment by moritzschepp** [comment] 2019-04-08 20:42
Sorry, I wasn't clear: The link doesn't resolve in my browser either but the error message doesn't say why its not working. The problem isn't the dot (by itself) because I can add `BMN_2002.33a-b_view1_bw` to my local installation as an identifier value and it resolves without problems. There should be a message in the production.log that tells us what's happening in your installation.

**Comment by Diederka** [comment] 2019-04-09 08:56
Oh, where can I find that message? how can I read the produczion log??? Im not familiar with that kind of things in the backend.

**Comment by moritzschepp** [comment] 2019-04-09 23:00
Its a file on the server KOR writes some information to (such as errors and access times). If you don't have access to it, please contact your data center. They should be able to retrieve the relevant information from the file.

**Comment by Diederka** [comment] 2019-04-11 10:13
Okay, the file was biiiig. 1,3 GB. I asked our IT specialist and he said that there is no lograte(?) He got the link and took only one time intervall from the error log. 
The following entry is created in production.log for the broken link:
`
I, [2019-04-11T11:36:54.368595 #12854]  INFO -- : Started GET
"/resolve/image_no/BMN_2002.33a-b_view1_bw" for 134.76.38.82 at
2019-04-11 11:36:54 +0200
I, [2019-04-11T11:36:54.370368 #12854]  INFO -- : Processing by
IdentifiersController#resolve as
I, [2019-04-11T11:36:54.370499 #12854]  INFO -- :   Parameters:
{"kind"=>"image_no", "id"=>"BMN_2002"}
I, [2019-04-11T11:36:54.415574 #12854]  INFO -- :   Rendered
layouts/404.html.erb within layouts/application (34.9ms)
I, [2019-04-11T11:36:54.415694 #12854]  INFO -- : Completed 500 Internal
Server Error in 45ms (ActiveRecord: 2.5ms)
F, [2019-04-11T11:36:54.416264 #12854] FATAL -- :
ActionView::Template::Error (undefined local variable or method `json'
for #<#<Class:0x000000066e59a0>:0x007f8ab8e4f828>
Did you mean?  JSON):
    4:   <title>NOT FOUND</title>
    5: </head>
    6: <body>
    7:   <p><%= json.message I18n.t('messages.not_found') %></p>
    8: </body>
    9: </html>
  app/views/layouts/404.html.erb:7:in
'_app_views_layouts_____html_erb___4263602226686938940_56679200'
  app/controllers/application_controller.rb:100:in `render_404'
`

**Comment by Diederka** [comment] 2019-04-11 10:16
haha, i didnt comment out the source code thus these strange signs. 
here is the code in a txt file
[productionlog_errorlog.txt](https://github.com/coneda/kor/files/3068087/productionlog_errorlog.txt)

**Comment by moritzschepp** [comment] 2019-04-11 17:20
Thanks! So it seems your installation is trying to render the "not found" page and fails while doing that. This is a bug and I will fix it shortly.

However, this does not fix your original problem. It seems the identifier object doesn't exist. Please try this and then report back if the resolving works again:

* untick the "Is identifier" checkbox from the `image_no` field configuration and save
* wait 10 minutes
* tick the "Is identifier" checkbox again and save
* wait 10 minutes

This should regenerate the identifier objects. Does that help?

**Comment by Diederka** [comment] 2019-04-17 08:39
I did that like you suggested. Waited a bit more than 10 minutes. But it didn't work.

**Comment by moritzschepp** [comment] 2019-04-17 17:11
In the console, can you run `Identifier.find_by(value: 'BMN_2002.33a-b_view1_bw')`, what's the output of that?

The background job is running? You can test it by uploading a new medium and see if the thumbnails are being generated.

**Comment by wuebbena** [comment] 2019-06-03 18:41
The problem itself is solved.

**Closed by wuebbena** 2019-06-03 18:41 UTC
Labels: bug, verification needed
