### ISSUE TITLE
Question: What options do i have to export my data apart from the csv format?

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#198] opened 2018-09-20 11:57 UTC
I mean how can I get JSON export output ? 
And where are the relations in the excel output? 
what else options do i have  ?

**Comment by moritzschepp** [comment] 2018-09-20 18:47
Did you have a look at the OAI-PMH and/or JSON APIs? The former is most suitable for large-scale data exports where completeness and repeatability are important. The latter is better suited for on-the-fly access by other applications. You can find more information in the [README](https://github.com/coneda/kor#interfaces), the official specification for OAI-PMH is hosted [here](https://www.openarchives.org/pmh/).

An example for the API Endpoints in Frankfurt are

OAI-PMH: https://kor.uni-frankfurt.de/api/oai-pmh/entities.xml?verb=ListRecords&metadataPrefix=kor
JSON https://kor.uni-frankfurt.de/entities.json

Both should also work in your installation. You can try them with your browser (or more systematically with cURL). Because of different default order, they do not show the same data.

**Comment by Diederka** [comment] 2019-01-30 13:09
One more question: If I want to edit data, I will probably do so with the excport excel. This means: I use the export Excel for changes and a self-created Ruby script will read it to apply the changes. Is that true? But what if I have to change relations? 
I don't find any relations in Export Excel. I find UUIDs but no relations. So how do I get all metadata including the relations via an export?

**Comment by moritzschepp** [comment] 2021-11-03 05:40
I close hoping that the issue is resolved by now, if not, please reopen.

**Closed by moritzschepp** 2021-11-03 05:40 UTC
Labels: question
