### ISSUE TITLE
Import Scripts are not able to edit existing data

### ISSUE THREAD

**Issue by Diederka** [coneda/kor#164] opened 2018-03-26 07:40 UTC
Our initial import rubyscripts read our uploaded csv tables to ingest initial imports. so far so good. but when we use them to edit existing data by changing the csv and using the script anew, no changes are made. 
is here some general info to solve this probem? or do you need specific info about our scripts for the solution?

**Comment by moritzschepp** [comment] 2018-03-26 22:47
The importer has a `-v` or `--verbose` flag. That should print a line about how it handled every line from the input file (and why). Does that yield any cluse?

**Comment by Diederka** [comment] 2018-04-24 09:57
no, i havent got any clue. what should the libnes print? and what should I change to be able to edit existing data? by reading the excel?  until now, we always deleted all entities and read the edited excel by the ruby scripts anew. that's the nexr problem. We only can delete ALL entities, not only for example the "Artefacts". you gave us the code to delete all entities,. but is there any way to delete only entities of one kind?

**Comment by moritzschepp** [comment] 2018-04-24 23:00
These are several questions:

To know what the import is doing with each Excel row, use the `-v` or `--verbose` flag.

To update existing records, make sure the identification columns are filled in, see also https://github.com/coneda/kor#excel-import-and-export. An easy workflow is to export the data with the Excel exporter, modify the data and import it again.

You can delete all entities of a kind by (e.g.) `Kind.find_by(name: 'Person').entities.destroy_all`. In KOR >= 2.1.0, this will only move the entities to a "trash bin", so they are still recoverable. If you would like to delete them entirely, use `Kind.find_by(name: 'Person').entities.each{|e| e.really_destroy!}` instead.

**Comment by Diederka** [comment] 2018-04-26 09:57
Sorry for putting 2 questions in. thanks for the answers. 
with your code I can delete different entities now . but they still  seem to have relations left, whne importing them anew, I cannot establish the relations anew. 
That brings us to the edit -question again. I think I use the export excel after a first ingest to edit the data. 
but how can I create such an export excel? And can I export only entities of certain kinds? or des it alweays export all entities of the different kinds in one table?

**Comment by moritzschepp** [comment] 2018-04-26 10:57
If you `destroy` or `really_destroy!` an entity, all relationships connected to it will be deleted as well. relations (think relationship types) are not deleted. I anderstand correctly that your installation, this is not the case?

You mean how to export to excel? Run `bundle exec bin/kor export --help` to see how the command works and what filters are available.

**Comment by moritzschepp** [comment] 2018-04-26 23:09
Hmm can you use the gems `byebug` or `pry` to check why the relationscript doesn't do the job the second time? You can find the public ruby gems repository here: https://rubygems.org/

**Comment by moritzschepp** [comment] 2021-11-03 05:30
I close hoping that the issue is resolved by now, if not, please reopen.

**Closed by moritzschepp** 2021-11-03 05:30 UTC
Labels: question
